# frontend/.gitlab-ci.yml
stages:
  # - build
  # - release
  - deploy

variables:
  VERSION: "1.0.${CI_PIPELINE_ID}"
  DOCKER_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/sausage-frontend:${VERSION}"
  NAMESPACE: std-ext-016-02
  MANIFEST_DIR: kubernetes/frontend


# build-frontend:
#   stage: build
#   image:
#     name: gcr.io/kaniko-project/executor:v1.9.0-debug
#     entrypoint: [""]
#   script:
#     - echo "Сборка и пуш фронтенда..."
#     - echo "${CI_REGISTRY_USER} ${CI_REGISTRY_PASSWORD} ${CI_PROJECT_DIR}"
#     - /kaniko/executor --context "${CI_PROJECT_DIR}/frontend" --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile" --destination "${DOCKER_IMAGE_NAME}" --build-arg VERSION=${VERSION} --cache=true


 
# release:
#   stage: release
#   image:
#     name: gcr.io/go-containerregistry/crane:debug
#     entrypoint: [""]
#   before_script:
#     - crane auth login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
#   script:
#     - crane tag ${DOCKER_IMAGE_NAME} ${VERSION}


deploy-frontend:
  stage: deploy
  image: alpine/k8s:1.31.12
  environment:
    name: production
    url: https://std-ext-016-02.k8s.praktikum-services.tech
  before_script:
    - apk add --no-cache openssh-client rsync

    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_DEPLOY" | tr -d '\r' | ssh-add -
    - mkdir -p /root/.ssh
    - chmod 700 /root/.ssh
    - echo "$SSH_KNOWN_HOSTS_DEPLOY" > /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/known_hosts
    - echo "CI_PROJECT_DIR='${CI_PROJECT_DIR}'"

    - mkdir  -p ~/.kube
    - echo "$KUBECONFIG_CONTENT" | base64 -d > ~/.kube/config
    - chmod 600 ~/.kube/config  
  script:
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "sudo rm -rf ~${CI_PROJECT_DIR}/kubernetes/frontend && sudo install -d -m 755 ~${CI_PROJECT_DIR}/kubernetes/frontend"
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "ls -la ~${CI_PROJECT_DIR}/kubernetes/"


    - cat ./kubernetes/frontend/configmap.yaml | ssh ${DEPLOY_USER}@${DEPLOY_HOST} "sudo tee ~${CI_PROJECT_DIR}/kubernetes/frontend/configmap.yaml   > /dev/null"
    - cat ./kubernetes/frontend/service.yaml     | ssh ${DEPLOY_USER}@${DEPLOY_HOST} "sudo tee ~${CI_PROJECT_DIR}/kubernetes/frontend/service.yaml   > /dev/null"
    - cat ./kubernetes/frontend/deployment.yaml  | ssh ${DEPLOY_USER}@${DEPLOY_HOST} "sudo tee ~${CI_PROJECT_DIR}/kubernetes/frontend/deployment.yaml > /dev/null"
    - cat ./kubernetes/frontend/deployment.yaml  | ssh ${DEPLOY_USER}@${DEPLOY_HOST} "sudo tee ~${CI_PROJECT_DIR}/kubernetes/frontend/ingress.yaml > /dev/null"
    - cat ./kubernetes/frontend/deployment.yaml  | ssh ${DEPLOY_USER}@${DEPLOY_HOST} "sudo tee ~${CI_PROJECT_DIR}/kubernetes/frontend/certificate.yaml > /dev/null"      

    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "echo "$KUBECONFIG_CONTENT" | base64 -d > ~/.kube/config"
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} " chmod 600 ~/.kube/config    "
    
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "kubectl apply -f ~${CI_PROJECT_DIR}/kubernetes/frontend -n ${NAMESPACE}"
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "kubectl set image deployment/frontend frontend=${DOCKER_IMAGE_NAME} -n ${NAMESPACE}"
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "kubectl rollout status deployment/frontend -n ${NAMESPACE} --timeout=120s"