stages:
  - build
  - release
  - deploy

variables:
  VERSION: "1.0.${CI_PIPELINE_ID}"
  DOCKER_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/sausage-frontend:${VERSION}"

cache:
  paths:
    - frontend/node_modules/

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "Building Docker image for frontend..."
    - /kaniko/executor --context "${CI_PROJECT_DIR}/frontend" --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile" --destination "${DOCKER_IMAGE_NAME}" --build-arg VERSION=${VERSION} --cache=true

release:
  stage: release
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  before_script:
    - crane auth login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - crane tag ${DOCKER_IMAGE_NAME} ${VERSION}


deploy:
  stage: deploy
  environment:
    name: production
    url: http://std-ext-016-xx.praktikum-services.tech
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # Создаём нужные директории на ВМ заранее
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "mkdir -p /tmp/${CI_PROJECT_DIR}/frontend"
    # - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "mkdir -p /tmp/frontend"
    
  script:
    - scp ./frontend/default.conf ${DEPLOY_USER}@${DEPLOY_HOST}:/tmp/${CI_PROJECT_DIR}/frontend/default.conf
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "ls -la /tmp/${CI_PROJECT_DIR}/frontend/default.conf"
    - scp ./frontend/deploy.sh ${DEPLOY_USER}@${DEPLOY_HOST}:/tmp/${CI_PROJECT_DIR}/frontend/deploy.sh
    - scp ./frontend/Dockerfile ${DEPLOY_USER}@${DEPLOY_HOST}:/tmp/${CI_PROJECT_DIR}/frontend/Dockerfile
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "chmod +x /tmp/${CI_PROJECT_DIR}/frontend/deploy.sh"
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "/tmp/${CI_PROJECT_DIR}/frontend/deploy.sh ${DOCKER_IMAGE_NAME} ${VERSION} ${CI_REGISTRY_USER} ${CI_REGISTRY_PASSWORD} ${CI_PROJECT_DIR}"