# .gitlab-ci.yml (в корне)
stages:
  - module-pipelines

frontend-pipeline:
  stage: module-pipelines
  trigger:
    include: frontend/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - frontend/**/*
        - kubernetes/frontend/**



backend-pipeline:
  stage: module-pipelines
  trigger:
    include: backend/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - backend/**/*
        - kubernetes/backend/**

backend-report-pipeline:
  stage: module-pipelines
  trigger:
    include: backend-report/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - backend-report/**/*
        - kubernetes/backend-report/**

 