stages:
  - build
  - release
  - deploy

variables:
  VERSION: "1.0.${CI_PIPELINE_ID}"
  DOCKER_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/sausage-backend:${VERSION}"

cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "Building Docker image for backend..."    
    - echo ${CI_PROJECT_DIR}
    - /kaniko/executor --context "${CI_PROJECT_DIR}/backend" --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile" --destination "${DOCKER_IMAGE_NAME}" --build-arg VERSION=${VERSION} --cache=true
    
release:
  stage: release
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  before_script:
    - crane auth login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - crane tag ${DOCKER_IMAGE_NAME} ${VERSION}

deploy:
  stage: deploy
  environment:
    name: production
    url: http://std-ext-016-02.praktikum-services.tech
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # Создаём нужные директории на ВМ заранее
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "mkdir -p /tmp/${CI_PROJECT_DIR}/backend" 
    # - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "mkdir -p /tmp/backend"
    
  script:
    - scp ./backend/deploy.sh ${DEPLOY_USER}@${DEPLOY_HOST}:/tmp/${CI_PROJECT_DIR}/backend/deploy.sh
    - scp ./backend/Dockerfile ${DEPLOY_USER}@${DEPLOY_HOST}:/tmp/${CI_PROJECT_DIR}/backend/Dockerfile
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "chmod +x /tmp/${CI_PROJECT_DIR}/backend/deploy.sh"
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "/tmp/${CI_PROJECT_DIR}/backend/deploy.sh \
        '${DOCKER_IMAGE_NAME}' \
        '${VERSION}' \
        '${CI_REGISTRY_USER}' \
        '${CI_REGISTRY_PASSWORD}' \
        '${SPRING_DATASOURCE_URL}' \
        '${SPRING_DATASOURCE_USERNAME}' \
        '${SPRING_DATASOURCE_PASSWORD}' \
        '${SPRING_DATA_MONGODB_URI}' '${CI_PROJECT_DIR}'"