#!/bin/bash

PSQL_ADMIN="<db user>"
PSQL_PASSWORD="<db password>"
PSQL_HOST="<your host>"
PSQL_PORT="6432"
PSQL_DBNAME="<db name>"
PSQL_CONNECTION="postgresql://${PSQL_ADMIN}:${PSQL_PASSWORD}@${PSQL_HOST}:${PSQL_PORT}/${PSQL_DBNAME}"

touch init.sql

# Очистим базу
echo "DROP TABLE IF EXISTS product;" >> init.sql
echo "DROP TABLE IF EXISTS orders;" >> init.sql
echo "DROP TABLE IF EXISTS order_product;" >> init.sql

# Создадим таблицы
echo "CREATE TABLE product(id bigint generated by default as identity, name varchar(255) not null, picture_url varchar(255), price double precision);" >> init.sql
echo "CREATE TABLE orders(id bigint generated by default as identity, status varchar(255), date_created date default current_date);" >> init.sql
echo "CREATE TABLE order_product(quantity integer not null, order_id bigint not null, product_id bigint not null);" >> init.sql

# Заполним таблицы
echo "INSERT INTO product (id, name, picture_url, price) VALUES (1, 'Сливочная', 'https://res.cloudinary.com/sugrobov/image/upload/v1623323635/repos/sausages/6.jpg', 320.00);" >> init.sql
echo "INSERT INTO product (id, name, picture_url, price) VALUES (2, 'Особая', 'https://res.cloudinary.com/sugrobov/image/upload/v1623323635/repos/sausages/5.jpg', 179.00);" >> init.sql
echo "INSERT INTO product (id, name, picture_url, price) VALUES (3, 'Молочная', 'https://res.cloudinary.com/sugrobov/image/upload/v1623323635/repos/sausages/4.jpg', 225.00);" >> init.sql
echo "INSERT INTO product (id, name, picture_url, price) VALUES (4, 'Нюренбергская', 'https://res.cloudinary.com/sugrobov/image/upload/v1623323635/repos/sausages/3.jpg', 315.00);" >> init.sql
echo "INSERT INTO product (id, name, picture_url, price) VALUES (5, 'Мюнхенская', 'https://res.cloudinary.com/sugrobov/image/upload/v1623323635/repos/sausages/2.jpg', 330.00);" >> init.sql
echo "INSERT INTO product (id, name, picture_url, price) VALUES (6, 'Русская', 'https://res.cloudinary.com/sugrobov/image/upload/v1623323635/repos/sausages/1.jpg', 189.00);" >> init.sql

echo "INSERT INTO orders (id, status, date_created) SELECT i, (array['pending', 'shipped', 'cancelled'])[floor(random() * 3 + 1)], DATE(NOW() - (random() * (NOW()+'90 days' - NOW()))) FROM generate_series(1, 10000000) s(i);" >> init.sql
echo "INSERT INTO order_product (quantity, order_id, product_id) SELECT floor(1+random()*50)::int, i, 1 + floor(random()*6)::int % 6 FROM generate_series(1, 10000000) s(i);" >> init.sql

psql ${PSQL_CONNECTION} -f init.sql

rm -f init.sql
