apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: std-ext-016-02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/std-ext-016-02/sausage-store/sausage-backend:1.0.2213670
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          env:
            # Эти переменные переопределяют те, что в ConfigMap
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://rc1a-vdrnhudsvsfj80g8.mdb.yandexcloud.net:6432/std-ext-016-02?ssl=true&sslmode=require
            - name: SPRING_DATASOURCE_USERNAME
              value: std-ext-016-02
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db-password
            - name: SPRING_DATASOURCE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db-database
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://std-ext-016-02:Testusr1234@rc1a-udg79n2h293n1hdk.mdb.yandexcloud.net:27018/std-ext-016-02?tls=true
            # Исправление ошибки с логами
            - name: LOG_PATH
              value: /tmp
            # Уменьшаем пул соединений с PostgreSQL
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
              value: "8"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "400m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: temp-reports-dir
          emptyDir: {}
      imagePullSecrets:
        - name: gitlab-registry