apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-report-config
  namespace: std-ext-016-02
data:
  application.properties: |
    spring.data.mongodb.uri=mongodb://std-ext-016-02:Testusr1234@rc1a-udg79n2h293n1hdk.mdb.yandexcloud.net:27018/std-ext-016-02?tls=true
